export const FETCH_JOBS = 'FETCH_JOBS';
export const FETCH_JOBS_START = 'FETCH_JOBS_START';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAIL = 'FETCH_JOBS_FAIL';

export const SET_JOBTYPE_FILTER = 'SET_JOBTYPE_FILTER';
export const SET_LOCATION_FILTER = 'SET_LOCATION_FILTER';
export const SET_GEOLOCATION_FILTER = 'SET_GEOLOCATION_FILTER';
export const SET_SEARCHTERM_FILTER = 'SET_SEARCHTERM_FILTER';


